# Generated by Django 2.0.1 on 2018-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogspost',
            options={'ordering': ['-createdate']},
        ),
        migrations.AlterField(
            model_name='blogspost',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogspost',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
